apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-brain
  namespace: sotto
  labels:
    app: agent-brain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-brain
  template:
    metadata:
      labels:
        app: agent-brain
    spec:
      containers:
        - name: agent-brain
          image: sotto-agent-brain:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MQTT_HOST
              value: mqtt-broker
            - name: MQTT_PORT
              value: "1883"
            - name: OLLAMA_URL
              value: http://ollama:11434
            - name: OLLAMA_MODEL
              value: llama3.1:8b
            - name: DB_PATH
              value: /data/sotto.db
            - name: VAULT_PATH
              value: /data/vault
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sotto-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sotto-data
  namespace: sotto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
