apiVersion: v1
kind: ConfigMap
metadata:
  name: sotto-mosquitto-config
  namespace: sotto
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    log_type all
    connection_messages true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sotto-mqtt-data
  namespace: sotto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sotto-mqtt
  namespace: sotto
  labels:
    app: sotto-mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sotto-mqtt
  template:
    metadata:
      labels:
        app: sotto-mqtt
        topology-group: balanced
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              topology-group: balanced
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: sotto-mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: sotto-mqtt-data
---
apiVersion: v1
kind: Service
metadata:
  name: sotto-mqtt
  namespace: sotto
spec:
  selector:
    app: sotto-mqtt
  ports:
    - port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: sotto-mqtt-nodeport
  namespace: sotto
spec:
  type: NodePort
  selector:
    app: sotto-mqtt
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31883
