apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sotto-ollama-data
  namespace: sotto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sotto-ollama
  namespace: sotto
  labels:
    app: sotto-ollama
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sotto-ollama
  template:
    metadata:
      labels:
        app: sotto-ollama
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-node4
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /root/.ollama
          startupProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sotto-ollama-data
---
apiVersion: v1
kind: Service
metadata:
  name: sotto-ollama
  namespace: sotto
spec:
  selector:
    app: sotto-ollama
  ports:
    - port: 11434
      targetPort: 11434
