apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcription
  namespace: sotto
  labels:
    app: transcription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcription
  template:
    metadata:
      labels:
        app: transcription
    spec:
      containers:
        - name: transcription
          image: sotto-transcription:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MQTT_HOST
              value: mqtt-broker
            - name: MQTT_PORT
              value: "1883"
            - name: WHISPER_MODEL
              value: base
            - name: WHISPER_DEVICE
              value: auto
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "4Gi"
